/**/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.133
    wheel_radius: 0.034

    # wheel_separation_multiplier: 1.0
    # left_wheel_radius_multiplier: 1.0
    # right_wheel_radius_multiplier: 1.0

    tf_frame_prefix_enable: true
    tf_frame_prefix: "brum/" # TODO: Make more modular

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_odom_tf: true

    position_feedback: true
    open_loop: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true

    # TODO: Figure out reasonable rotational limits

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.max_velocity: 0.569675468
    linear.x.min_velocity: -0.569675468
    # linear.x.max_acceleration: 1.0

    angular.z.max_velocity: 8.56654839098 
    angular.z.min_velocity: -8.56654839098 
    # angular.z.max_acceleration: 1.0
    # angular.z.min_acceleration: -1.0