<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_width" value="0.025"/>

  <material name="wheel_material">
    <!-- <color rgba="0.79216 0.81961 0.93333 1" /> -->
    <color rgba="${235/255} ${216/255} ${52/255} 1" />
  </material>

  <link name="left_wheel">
    <inertial>
      <origin xyz="-1.8593E-08 -1.3155E-09 -0.011873" />
      <mass value="0.16695" />
      <inertia
        ixx="6.7296E-05"
        ixy="5.9539E-12"
        ixz="3.2303E-12"
        iyy="6.7293E-05"
        iyz="2.4005E-13"
        izz="0.00011321" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://brum_description/meshes/left_wheel.STL" />
      </geometry>
      <material name="wheel_material"/>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 -${wheel_width/2}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>
  <link
    name="right_wheel">
    <inertial>
      <origin xyz="-1.8593E-08 -1.3155E-09 -0.011873" />
      <mass value="0.16695" />
      <inertia
        ixx="6.7296E-05"
        ixy="5.9539E-12"
        ixz="3.2304E-12"
        iyy="6.7293E-05"
        iyz="2.4005E-13"
        izz="0.00011321" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://brum_description/meshes/right_wheel.STL" />
      </geometry>
      <material name="wheel_material"/>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${-wheel_width/2}"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <origin
      xyz="0 0.07925 -0.01815"
      rpy="-1.5708 0 0" />
    <parent link="frame_link" />
    <child link="left_wheel" />
    <axis xyz="0 0 1" />
  </joint>
  <joint name="right_wheel_joint" type="continuous">
    <origin
      xyz="0 -0.07925 -0.01815"
      rpy="1.5708 0 0" />
    <parent link="frame_link" />
    <child link="right_wheel" />
    <axis xyz="0 0 -1" />
  </joint>
</robot>